version: '2.3'

services:
  omnisci-core:
    image: 'mapd/mapd-ce-cuda'
    ports:
      - 9090:9090
      - 9091:9091
      - 9092:9092
    volumes:
      - ./data:/mapd-storage
    ipc: host
    runtime: nvidia

  workshop-genelab:
    image: 'workshop-genelab'
    ports:
      - 8888:8888
    links:
      - omnisci-core
    ipc: host
    runtime: nvidia
